modLoader = "javafml"
loaderVersion = "[41,)"
issueTrackerURL = "https://github.com/Sweenus/SimplySwords/issues"
license = "Timefall Development License"

[[mods]]
modId = "simplyswords"
version = "${version}"
displayName = "Simply Swords"
authors = "Sweenus"
credits="Konsyliarz42 (Artist)"
description = '''
A variety of unique weapons to add to your minecraft repertoire
'''
logoFile = "SimplySwordsLogoFinal2.gif"

[[dependencies.simplyswords]]
modId = "forge"
mandatory = true
versionRange = "[41,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.simplyswords]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.simplyswords]]
modId = "architectury"
mandatory = true
versionRange = "[5.12.42,)"
ordering = "AFTER"
side = "BOTH"